config/routes.rb
 Rails.application.routes.draw do

  root 'testers#index'

  namespace :users do

    resources :registrations, except: :destroy do
      collection do
        get 'is_emails_exist'
      end
    end

    resources :sessions, only: [:new, :destroy] do
      collection do
        post 'auth'
      end
    end

    resources :passwords, only: [:edit, :update] do
      collection do
        get 'reset'
        get 'callback_reset'
        get 'edit_reset'
        put 'update_reset'
      end
    end

    resources :mailers, only: [] do
      collection do
        get 'send_confirmation'
        post 'send_reset_password'
        get 'send_novice_task'
      end
    end

    get '/id_cards', to: 'id_cards#edit'
    get '/id_cards/show',  to: 'id_cards#show'
    post '/id_cards', to: 'id_cards#create'
    put '/id_cards',  to: 'id_cards#update'

    get 'alipay', to: 'pays#alipay'
    post 'alipay_callback', to: 'pays#alipay_callback'
    post 'alipay_exception_callback', to: 'alipay_exception_callback'

    get 'wxpay',  to: 'pays#wxpay'
    post 'wxpay_callback', to: 'pays#wxpay_callback'

    resources :reward_records, only: [:index, :show, :create]
    resources :integral_records, path: :records, only: :index

  end

  resources :rewards, only: :index
  resources :pms
  resources :projects do
    collection do
      get 'web/new', to: 'projects#web'
      get 'app/new', to: 'projects#app'
    end

    member do
      get 'video/:assignment_id', to: 'projects#video'
    end
  end

  resources :testers do
    collection do
      get 'help'
      get 'how-to-get-five-star', to: 'testers#rating_help'
      get 'choose-device', to: 'testers#choose'
    end
  end

  resources :assignments do
    resources :feedbacks

    collection do
      get 'fresh'
      get 'finish'
      get 'join'
      get 'ing'
      get 'done'
      get 'upload'
      get 'qr_token'
      get 'upload_token'
      get 'get_video'
      delete 'delete_video'
    end

     member do
      post 'callback_from_qiniu'
      post 'callback_from_qiniu_transfer'
      post 'callback_from_qiniu_video_images'
      post 'rating'

      get 'got_it'
      get 'subscribe'
      get 'unsubscribe'
    end

  end

  namespace :stores do
    root to: "base#index"
    get 'help', to: 'base#help'
    resources :goods do
      collection do
        post 'new',  to: 'goods#save_picture'
      end
      member do
        get 'lookup', to: 'goods#lookup'
        post 'edit',  to: 'goods#save_picture'
      end

      resources :skus
    end
    resources :orders
    resources :pictures, only: :create
  end

  # admin
  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'
  namespace :dashboard, path: '/admin' do
    root 'charts#index'
    resources :charts, only: [] do
      get 'select', to: 'charts#select', on: :collection
    end
    resources :videos, controller: :assignments do
      get 'search', to: 'assignments#search', on: :collection
    end
    resources :users do
      get 'search', to: 'users#search', on: :collection
    end
    resources :projects do
      get 'search', to: 'projects#search', on: :collection
      member do
        get 'select'
        post 'deliver'
      end
    end
    resources :goods do
      post 'search', to: "goods#search", on: :collection
      resources :skus do
        collection do
          put 'create_or_update', to: 'skus#create_or_update'
        end
      end
    end
    resources :orders, only: [:index, :edit, :destroy] do
      get 'search', to: "orders#search", on: :collection
      member do
        get 'virtual'
        get 'real'
      end

      resources :skus, only: :update
      resources :addresses, only: :update
    end
    resources :rewards
    resources :id_cards
    resources :reward_records do
      collection do
        get 'export'
        get 'search'
      end
    end

  end

  resource :wechat, only: [:show, :create]

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == Settings.sidekiq_username && password == Settings.sidekiq_password
  end if Rails.env.production?
  mount Sidekiq::Web, at: '/sidekiq'

  resources :errors, only: [] do
    get 'file_not_found'
    get 'unprocessable'
    get 'internal_server_error'
  end

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  if Rails.env.production?
    match "*path", to: "errors#file_not_found", via: :all
  end

end

app/models/reward.rb
class Reward < ActiveRecord::Base

  has_many :orders
  default_scope { order('cost') }
  scope :show,  -> { where(publish: true) }

  validates :name, :amount, :cost, presence: true

end

app/controllers/dashboard/rewards_controller.rb
class Dashboard::RewardsController < Dashboard::BaseController

  load_and_authorize_resource
  before_action :get_reward, only: [:show, :edit, :destroy, :update]

  def index
    @rewards = Reward.page(params[:page])
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      redirect_to dashboard_reward_path(@reward)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @reward.update_attributes(reward_params)
      redirect_to dashboard_rewards_path
    else
      render :edit
    end
  end

  def destroy
    @reward.destroy

    redirect_to dashboard_rewards_path
  end


private

  def reward_params
    params.require(:reward).permit(:name, :cost, :amount, :publish)
  end

  def get_reward
    @reward = Reward.find params[:id]
  end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  before_action :require_login?

  def index
    @rewards = Reward.show
  end

end

app/controllers/users/rewards_controller.rb
class Users::RewardsController < ApplicationController

  include WechatsTicketable

  before_action :require_login?

  def index
    @records = current_user.reward_records.page(params[:page])
  end

  def create
    json = { status: 0, code: 1, msg: '兑换成功' }

    unless current_user.id_card&.status == true
      json[:code], json[:msg] = 0, '还未认证成功！'
      return render json: json
    end

    reward = Reward.where(id: params[:id]).first
    unless reward
      json[:code], json[:mgs] = -1, '没有这个红包'
      return render json: json
    end

    ActiveRecord::Base.transaction do
      credits = current_user.credits - reward.cost
      if credits < 0
        json[:code], json[:mgs] = -2, '积分不足'
        return json
      else
        @order = current_user.orders.build(total_cost: reward.cost,
                                           type: 'reward',
                                           reward_id: reward.id)

        get_ticket

        if @order.save
          @reward_record = current_user.reward_records.build(order_id: @order.id,
                                                             amount: reward.cost,
                                                             id_num: current_user.id_card.id_num,
                                                             name: current_user.id_card.name,
                                                             secret: @secret)
          if @reward_record.save
            current_user.update_column(:credits, credits)
          else
            json[:code], json[:msg] = -3, '兑换失败'
          end
        else
          json[:code], json[:msg] = -3, '兑换失败'
        end
      end
    end

    return render json: json
  end

  def show
    get_ticket
  end

  def destroy
  end

end

app/helpers/rewards_helper.rb
module RewardsHelper
  def icon_href(amount)
    "http://7xjciz.com2.z0.glb.qiniucdn.com/reward-#{amount.to_i}.png"
  end
end

app/views/rewards/index.html.slim
.geeklab-container
  .reward-record
    .reward-record-header.clearfix
      .reward-record-title
        span
          | 红包兑换
        span.exchange-exp
          | (兑换公式: 100积分 = 10 元红包)
      .credit-record
        a href="#{users_reward_records_path}" target="_blank" style="margin-right: 10px"
          | 红包记录
        span
          | 我的积分
        span.icon-img.icon-outer-18 style="margin: 0 5px -4px 10px"
          i.icon-inner.icon-score-old
        span
          = current_user.to_tester.credits
    .reward-record-content.clearfix
      .clearfix
        .reward-exchange-list
          - @rewards.each do |reward|
            .reward-item
              .reward-icon
                img src="#{icon_href(reward.amount)}"
              .reward-form-control
                .radio-cos
                  input id=("reward-#{reward.amount.to_i}") type="radio" name="reward" value="#{reward.to_params}"
                  .radio-icon
                label for=("reward-#{reward.amount.to_i}")
                  span.icon-img.icon-outer-18 style="margin: 0 5px -4px 5px"
                    i.icon-inner.icon-score-old
                  = reward.cost.to_i
      .reward-exchange-tools
        .reward-hint style="display: none"
          | 请选择兑换金额
        .reward-exchange-button
          - if current_user.id_card && current_user.id_card.status === 'success'
            #reward-submit.btn.btn-flat.blue.btn-rounded.btn-m
              | 我要兑换
          - else
            - if !current_user.id_card
              a.btn.btn-flat.blue.btn-rounded.btn-m href="#{users_id_cards_path}"
                | 先去实名认证
            - else
              - if current_user.id_card.status === 'failed'
                a.btn.btn-flat.blue.btn-rounded.btn-m href="#{users_id_cards_path}"
                  | 先去实名认证
              - else
                a.btn.btn-flat.blue.btn-rounded.btn-m href="#{users_id_cards_show_path}"
                  | 先去实名认证
        .reward-exchange-link
          a href="#{stores_root_path}" target="_blank"
            | 兑换其它礼品

= render 'users/shared/reward_qrcode'